### PR TITLE
Bump minimum `node` version.

### LINKED ISSUE #4: Consider dropping support for older `node` versions.
Mostly so you can use `Object.assign` instead of `defaults` and save some upstream packages a couple of transitive dependencies.  Not a great reason, but I'd love to make a PR for it or something.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
To `node>=4`.  Closes #4.

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
CI is failing.  Is there something I should do?

**Comment by realityking** [comment]
Looks like CI is failing because there's no `.travis.yml`. Not sure if @timoxley is willing to merge this PR but you could simply add a `.travis.yml` to get this PR into a mergeable state.

**Comment by styfle** [comment]
Try adding a file `.travis.yml` with the following:


```yml
branches:
  only:
    - "master"

git:
  depth: 3

language: node_js

node_js:
  - "4"
  - "10"

script:
  - npm run test
```

**Review by styfle — APPROVED** [review]
LGTM 👍

**Comment by styfle** [comment]
@timoxley What do you think?

**Comment by realityking** [comment]
I‘d add node 6 and 8 for safety otherwise 👍

**Comment by realityking** [comment]
@timoxley Could you check this one out? Thank you!

**Comment by ayonious** [comment]
@timoxley any update on this one? could you please approve and merge this?

**Pull request closed without merging**
